//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWIX.Models.DataWarehouse
{
    using System;
    
    [Serializable]
    public partial class TopProject
    {
        public string MarketName { get; set; }
        public string CountyName { get; set; }
        public string Zipcode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<int> TotalUnitsPlanned { get; set; }
        public Nullable<decimal> ClosingsMedianPrice { get; set; }
        public Nullable<short> ClosingCount { get; set; }
        public string ProductTypeLongDesc { get; set; }
        public string WebAddress { get; set; }
    }
}
